version: '3'

services:
  redis:
    image: redis:4
    container_name: redis
    hostname: redis
    ports:
      - 6479:6379
    logging:
      driver: 'json-file'
      options:
        max-size: '2m'
        max-file: '5'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
    networks:
      - code-network

  mariadb:
    image: mariadb/server:10.3
    restart: always
    container_name: mariadb
    hostname: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: wedding-api
      MARIADB_USER: wedding-api
      MARIADB_PASSWORD: wedding-api
      MARIADB_DATABASE: wedding-api
      TZ: "Asia/Jakarta"
    volumes:
      - ./mydb:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - code-network