version: 0.2
phases:
  install:
    commands:
      - echo install steps...
  pre_build:
    commands:
      # run migration development here
      - echo Logging into AWS ECR...
      - $(aws ecr get-login --no-include-email --region ap-southeast-1)
      - REPOSITORY_URI=583459700509.dkr.ecr.ap-southeast-1.amazonaws.com/wedding-api-prd
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo  pulling latest docker images.
      - echo build Docker image
      - docker pull $REPOSITORY_URI:$IMAGE_TAG
      - docker run -v $PWD/config:/opt/wedding-api/config $REPOSITORY_URI:$IMAGE_TAG /bin/bash -c "/opt/wedding-api/wedding-api db:migrate up"