definitions:
  appctx.Response:
    properties:
      data:
        type: object
      errors:
        type: object
      message:
        type: object
      name:
        type: string
    type: object
  presentations.ExampleCreate:
    properties:
      address:
        type: string
      email:
        type: string
      name:
        type: string
      phone:
        type: string
    required:
    - address
    - email
    - name
    - phone
    type: object
info:
  contact: {}
  license: {}
paths:
  /ex/v1/example/create:
    post:
      consumes:
      - application/json
      description: project_service Example case for creating APIs
      parameters:
      - description: Example Case Payload
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/presentations.ExampleCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/appctx.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/appctx.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/appctx.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/appctx.Response'
      summary: project_service Example Create
      tags:
      - project_service
  /in/health:
    get:
      consumes:
      - application/json
      description: testing Check service health from server environment
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/appctx.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/appctx.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/appctx.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/appctx.Response'
      summary: testing Check Health Status
      tags:
      - testing
swagger: "2.0"
