FROM golang:1.14.2-alpine3.11 as builder

ARG GO_BUILD_COMMAND="CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w' -o wedding-api src/main.go"

# Install some build deps + ssh tools for the setup below.
RUN apk update && apk --no-cache add  build-base  git bash  coreutils openssh  openssl


# this command if you get source from bitbucket repos
# Create the directory where the application will reside
RUN mkdir -p /go/src/github.com/otoraja/wedding-api


WORKDIR /go/src/github.com/otoraja/wedding-api

COPY . .


# application builder step
RUN go mod tidy && go mod download && go mod vendor
RUN eval $GO_BUILD_COMMAND


# STEP 2 build a small image
# Set up the final (deployable/runtime) image.
FROM alpine:3.10.2


# setup package dependencies
RUN apk --no-cache update && apk --no-cache  add  ca-certificates bash jq curl

ENV BUILDDIR=/go/src/github.com/otoraja/wedding-api
ENV PROJECT_DIR=/opt/wedding-api

# Setting timezone
ENV TZ=Asia/Jakarta
RUN apk add -U tzdata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#create project directory
RUN mkdir -p $PROJECT_DIR/config
RUN mkdir -p $PROJECT_DIR/database/migration

WORKDIR $PROJECT_DIR

COPY --from=builder $BUILDDIR/wedding-api wedding-api
COPY --from=builder $BUILDDIR/database/migration $PROJECT_DIR/database/migration
COPY --from=builder $BUILDDIR/config/msg.yaml $PROJECT_DIR/config/msg.yaml
COPY --from=builder $BUILDDIR/.env $PROJECT_DIR/.env


CMD ["sh","-c", "/opt/wedding-api/wedding-api http serve"]
